### Create a new expenditure
POST http://localhost:8080/expenditures
Content-Type: application/json

{    
    "description": "Groceries",
    "amount": 76.00,
    "date": "2025-04-15T12:00:00Z"
}


### Retrieve all expenditures
GET http://localhost:8080/expenditures

### Retrieve a specific expenditure by ID
GET http://localhost:8080/expenditures/9d523af2-a92f-4805-b0f0-997bcc5ac471

### Update a specific expenditure by ID
PUT http://localhost:8080/expenditures/9d523af2-a92f-4805-b0f0-997bcc5ac471
Content-Type: application/json

{
   "description": "Candy for kids",
   "amount": 4.75,
   "date": "2023-12-25T12:00:00Z"
}

### Delete a specific expenditures by ID
DELETE http://localhost:8080/expenditures/812484df-af37-4414-bb33-4a316a2d4bbf
